[Interface]
# VPN Accelerator
PrivateKey=6KYOFJcseqWM9rFXN9WE6dHQKRYHeblnPl8nXUigDE0=
Address=10.2.0.2
PostUp=logger -t wireguard -- 'Tunnel WireGuard-wg0 started';/usr/local/emhttp/webGui/scripts/update_services
PostDown=logger -t wireguard -- 'Tunnel WireGuard-wg0 stopped';/usr/local/emhttp/webGui/scripts/update_services
PostUp=ip -4 route flush table 200
PostUp=ip -4 route add default via 10.2.0.2 dev wg0 table 200
PostUp=ip -4 route add 192.168.10.0/24 via 192.168.10.1 dev br0 table 200
PostDown=ip -4 route flush table 200
PostDown=ip -4 route add unreachable default table 200
PostDown=ip -4 route add 192.168.10.0/24 via 192.168.10.1 dev br0 table 200

[Peer]
# CH-US3
PublicKey=j+clV7yQPWWhQ7v4/8AWBzZ5DNUGSvruZAIsVtyZ92A=
Endpoint=62.169.136.247:51820
AllowedIPs=0.0.0.0/0
