[global]
socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=131072 SO_SNDBUF=131072
server min protocol = SMB3
use sendfile = yes
aio read size = 4096
aio write size = 4096
min receivefile size = 16384
getwd cache = yes
strict locking = no
server signing = auto
client signing = disabled